-- 코드를 작성해주세요
SELECT AN.ITEM_ID AS ITEM_ID, II.ITEM_NAME AS ITEM_NAME, II.RARITY AS RARITY
FROM 
(SELECT IT.ITEM_ID AS ITEM_ID
FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT
WHERE II.RARITY = 'RARE' AND II.ITEM_ID = IT.PARENT_ITEM_ID) AS AN
JOIN ITEM_INFO AS II
WHERE AN.ITEM_ID = II.ITEM_ID
ORDER BY ITEM_ID DESC;
